Docker
1Revenger1/Wylx pull request #136
Opened 2024-09-10 01:38 UTC by 1Revenger1

2024-09-21 04:42 UTC, joshuamb419 requested changes
Everything except env comment lgtm

2024-09-21 04:42 UTC, joshuamb419 commented on src/main/java/com/wylxbot/wylx/Core/Util/EnvUtils.java
I know WylxEnvConfig.java is currently just the .env files but I strongly feel that this belongs in there setting a variable instead of being a method that is called any time we check if Wylx is running in docker. Its not like thats going to change mid run, its an env variable and as such should be in the same file.

2025-02-23 22:03 UTC, 1Revenger1 commented
This publishes automatically now to github container registry. Need a PAT (private access token) to pull it which is a pain but oh well.

2025-07-12 16:43 UTC, joshuamb419 submitted a review, later dismissed

2025-10-13 02:53 UTC, averycblack reviewed
Added some comments to make this easier to review, especially since things have changed over the year. Main features:
- Creates a Wylx container based on an Alpine JRE image
- Add example .env file documentation
- Embed version information within the JAR
- Github pipeline to automatically publish Wylx containers to ghrc.io

2025-10-13 02:53 UTC, averycblack commented on .github/workflows/publish.yaml
Creates docker images and publishes them to ghrc.io for others to pull down.
Creates sha256 tags as well as a `latest` tag that always points to the latest commit

2025-10-13 02:53 UTC, averycblack commented on Dockerfile
Wylx container definition. Runs Wylx as user 1000 (non-root).
Based on the Alpine containers which use musl instead of glibc.

2025-10-13 02:53 UTC, averycblack commented on build.gradle
Adds an extra gradle task to add version/build-date to a properties file embedded within the JAR.
Additionally standardizes the jar/zip name to not include the version to make the docker container easier to assemble.

2025-10-13 02:53 UTC, averycblack commented on compose.yaml
Example docker compose file which should work for dev purposes.

2025-10-13 02:53 UTC, averycblack commented on run.ps1
`--build` to rebuild the Wylx container everytime docker compose up is ran. Without this, docker compose will use old containers even if files have been changed.

2025-10-13 02:53 UTC, averycblack commented on src/main/java/com/wylxbot/wylx/Commands/BotUtil/UpdateCommand.java
Prevent updating in docker container

2025-10-13 02:53 UTC, averycblack commented on src/main/java/com/wylxbot/wylx/Commands/BotUtil/StatusCommand.java
Move commit detection to build.gradle script with parsing in WylxEnvConfig.java

2025-10-13 02:53 UTC, averycblack commented on src/main/java/com/wylxbot/wylx/Core/WylxEnvConfig.java
Parse commit/date properties from embedded properties file generated by Gradle.
Also detects if Wylx is running in a docker container to prevent updates/have accurate system info.

2025-10-13 03:19 UTC, averycblack commented on src/main/java/com/wylxbot/wylx/Core/Util/EnvUtils.java
I moved this logic into WylxEnvConfig.java

2025-11-12 04:01 UTC, joshuamb419 commented on src/main/java/com/wylxbot/wylx/Commands/BotUtil/UpdateCommand.java
If the expected use going forwards is through a docker container we should remove the self update function entirely imo. If you have objections I'm fine leaving it but just don't want to be supporting more deployments than we should

2025-11-12 04:01 UTC, joshuamb419 commented on build.gradle
I don't know the git commands off the top of my head, but what does this mean for version numbering? Is the version just becoming a sha or are we switching to a system where we're required to tag releases?

2025-11-12 04:05 UTC, averycblack commented on build.gradle
SHA unless we put down a tag

2025-11-12 04:06 UTC, averycblack commented on src/main/java/com/wylxbot/wylx/Commands/BotUtil/UpdateCommand.java
I'm good with that. Let me remove real quick.

2025-11-12 04:12 UTC, joshuamb419 approved these changes

2025-11-12 04:13 UTC, merged