6 server management commands
1Revenger1/Wylx pull request #22
Opened 2022-01-22 23:53 UTC by SnakeJ419

2022-01-29 23:06 UTC, SnakeJ419 commented
Should probably be more added command but i think this is enough for one pr

2022-01-29 23:34 UTC, 1Revenger1 requested changes

2022-01-29 23:34 UTC, 1Revenger1 commented on src/main/java/Commands/Management/CleanCommand.java
> +            cleanMessages(event.getChannel().getHistory(), 20);
Early return maybe? Reduce the tab depth of try/catch before

2022-01-29 23:34 UTC, 1Revenger1 commented on src/main/java/Commands/Management/CleanCommand.java
> +                    if(i < scrapeThisTime-1 && messages.get(i+1).getContentRaw().length() > 1  && messages.get(i+1).getContentRaw().charAt(0) == prefix){
prefix can be longer then a character. Also couldn't you just check the message from the event instead of looking for prefix or whatever? Why check to begin with?

2022-01-29 23:34 UTC, 1Revenger1 commented on src/main/java/Commands/Management/CleanCommand.java
> +            if(scrape > 100){
```suggestion
            
            if(scrape > 100){
```

2022-01-30 00:02 UTC, 1Revenger1 approved these changes

2022-01-30 00:03 UTC, merged