Toggleable commands
1Revenger1/Wylx pull request #45
Opened 2022-03-30 01:23 UTC by SnakeJ419

hahahhahahahahhaha

2022-03-31 00:46 UTC, 1Revenger1 requested changes
This PR was kind of a pain to understand. Is it possible to split up in the future (ie DB stuff in one PR, Package move in another?)

I don't think we need exceptions for a module. We can already disable events individually. I'm still iffy on needing individual event toggles too.

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Commands/Frog/FrogPackage.java
> +		);
Ditto on formatting

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Commands/DND/TTRPGPackage.java
> +		);
Also this is tabs instead of spaces.

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Commands/Music/MusicPackage.java
> +		);
Ditto on formatting

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Database/DiscordServer.java
> +    public <T> void setSetting(ServerIdentifiers identifier, Object data) {
Are we able to use `<T> data` instead of `Object data` here? Would save on a cast below. It's fine if not.

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Database/DiscordServer.java
> +    private CodecRegistry getServerCodecRegistry() {
Can you comment this please?

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Core/Processing/MessageProcessing.java
> +
Formatting

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Core/Events/ServerEventManager.java
> +	private final HashMap<String, Boolean> eventExceptionMap = new HashMap<>();
Why should there be exceptions? This feels like unnecessary complexity. We can already disable commands individually.

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Core/Events/ServerEventManager.java
> +			masterEventMap.put(eventName, value);
Ditto

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Core/Events/ServerEventManager.java
> +		moduleMap.put(moduleName, value);
Don't need to remove from map before settting new value.

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Core/Events/ServerEventManager.java
> +			masterEventMap.put(eventName, value);
This looks like it doesn't save if the event was disabled before setting the module. Is this intended?

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Commands/ServerSettings/EnableCommand.java
> +			ctx.event().getChannel().sendMessage("Event \"" + eventName + "\" does not exist").queue();
Exception doesn't necessarily mean that event does not exist. Should probably specify the exception in setEvent or whatever, and just print the description of it here.

2022-03-31 00:46 UTC, 1Revenger1 commented on src/main/java/Core/Events/ServerEventManager.java
> +		if(write) serverDB.setSetting(ServerIdentifiers.Modules, this);
Enabling/Disabling a module and writing it to the DB should be two seperate steps I think. I wouldn't write here.

2022-03-31 01:40 UTC, SnakeJ419 commented on src/main/java/Core/Events/ServerEventManager.java
> +			masterEventMap.put(eventName, value);
Yes that behavior is intended, I had .replace originally, but if the value isn’t there at the time of replace then nothing will get set. And we don’t want to have multiple copies of one event within the map

2022-03-31 01:40 UTC, SnakeJ419 commented on src/main/java/Core/Events/ServerEventManager.java
> +		moduleMap.put(moduleName, value);
See above, we do

2022-03-31 01:42 UTC, SnakeJ419 commented on src/main/java/Core/Events/ServerEventManager.java
> +		if(write) serverDB.setSetting(ServerIdentifiers.Modules, this);
Why should writing be separate steps? Any time it’s changed we want that change to be reflected in the db and the only time we’re making more than one change in succession is when loading from the db which we already don’t write for

2022-03-31 01:52 UTC, SnakeJ419 commented on src/main/java/Core/Events/ServerEventManager.java
> +			masterEventMap.put(eventName, value);
well thats just dumb

2022-03-31 01:53 UTC, SnakeJ419 commented on src/main/java/Database/DiscordServer.java
> +    public <T> void setSetting(ServerIdentifiers identifier, Object data) {
honestly have no clue, ill try it with that but it was an object before so im not sure if theres a reason for that or not

2022-04-01 02:45 UTC, Jerbilcraft commented on src/main/java/Commands/DND/TTRPGPackage.java
> +		);
do we have a preferred code linter and format document yet to check style and formatting? It could be easier to correct this all if we did

2022-04-01 02:50 UTC, Jerbilcraft commented on src/main/java/Commands/ServerUtil/ServerUtilPackage.java
> +		);
small formatting change needed

2022-04-01 02:56 UTC, Jerbilcraft commented on src/main/java/Core/Events/EventPackage.java
> +        for(Event event : events){
would we want to print all the commands in a package as disabled as well if we already know the package is disabled or is this mostly to print the commands that are enabled individually in a package even if the package is disabled?

2022-04-01 02:57 UTC, SnakeJ419 commented on src/main/java/Commands/ServerUtil/ServerUtilPackage.java
> +		);
avery has already mentioned as much

2022-04-01 02:58 UTC, Jerbilcraft reviewed
I marked the files I feel need no changes as viewed and the rest may need changes ore have unresolved comments

2022-04-01 03:05 UTC, SnakeJ419 commented on src/main/java/Core/Events/EventPackage.java
> +        for(Event event : events){
my thought process was that putting (Disabled) or (Enabled) after every command would be to many things for the user to look at so I decided it would be better to show the state of the package and then only add a tag to the command if it was different. You can see what that looks like [here](https://discord.com/channels/932502244664946708/932748379971268639/958565812065677382l). What do you think?

2022-04-04 19:18 UTC, SnakeJ419 commented on src/main/java/Database/DiscordServer.java
> +    public <T> void setSetting(ServerIdentifiers identifier, Object data) {
Wasn't able to do that because the type of data changes partway through lol

2022-04-06 23:54 UTC, 1Revenger1 commented on src/main/java/Commands/DND/TTRPGPackage.java
> +		);
We probably should. Not this PR though

2022-04-06 23:55 UTC, 1Revenger1 commented on src/main/java/Database/DiscordServer.java
> +        // Go through items in the database to see if they have a custom codec, if the do add their codec to the codecs
Lol, you didn't need this many comments. Mostly just wanted a comment saying what the function did.

2022-04-06 23:57 UTC, SnakeJ419 commented on src/main/java/Database/DiscordServer.java
> +        // Go through items in the database to see if they have a custom codec, if the do add their codec to the codecs
~~next pr is commented like this lol~~

2022-04-07 00:26 UTC, 1Revenger1 requested changes
I still think that enabling/disabling individual commands is overkill, but it looks fine. I'd rather just get this in and refactor later. One thing with tabs

2022-04-07 00:42 UTC, 1Revenger1 approved these changes

2022-04-07 00:42 UTC, merged