addroles
1Revenger1/Wylx pull request #56
Opened 2022-04-10 05:07 UTC by 1Revenger1

2022-04-12 22:47 UTC, SnakeJ419 requested changes
Overall architecture is sound

2022-04-12 22:47 UTC, SnakeJ419 commented on src/main/java/Commands/Roles/RoleCommand.java
> +        if (!guild.getSelfMember().hasPermission(Permission.MANAGE_ROLES)) {
put this warning also in add roles so that admins are reminded to give wylx the right permission

2022-04-12 22:47 UTC, SnakeJ419 commented on src/main/java/Commands/Roles/RoleCommand.java
> +    private void roleListEmbed(CommandContext ctx, List<Role> rolesDb) {
Move to RoleUtil and make also show when adding/removing roles from the public roles list maybe? or is that to much

2022-04-12 22:47 UTC, SnakeJ419 commented on src/main/java/Commands/Roles/RoleCommand.java
> +        super("role", CommandPermission.EVERYONE, "List and assign roles");
Add usage example to command description

2022-04-12 22:47 UTC, SnakeJ419 commented on src/main/java/Commands/Roles/RemoveRoleCommand.java
> +                "Remove role from list of roles which users can self-assign. Can be a comma-delimited list" +
show usage example

2022-04-12 22:47 UTC, SnakeJ419 commented on src/main/java/Commands/Roles/AddRoleCommand.java
> +                        " (addrole role1, role2, role3, ...)");
show usage example

2022-04-12 22:47 UTC, SnakeJ419 commented on src/main/java/Core/Role/RoleUtil.java
> +package Core.Role;
This should be in with the roles package not sure why its in core

2022-04-12 23:10 UTC, 1Revenger1 commented on src/main/java/Core/Role/RoleUtil.java
> +package Core.Role;
I thought the Commands.Roles package was just for commands? I usually put utility and stuff in Core.x

2022-04-12 23:15 UTC, 1Revenger1 commented on src/main/java/Commands/Roles/RoleCommand.java
> +    private void roleListEmbed(CommandContext ctx, List<Role> rolesDb) {
Maybe could list roles it added? I don't think the full list needs to be shown every time a role is added or removed.

2022-04-12 23:16 UTC, SnakeJ419 commented on src/main/java/Core/Role/RoleUtil.java
> +package Core.Role;
But it's not core stuff? I'd say that type of things should go with the commands. Music you had to build a lot of core infrastructure for which is why I thought it was in core

2022-04-12 23:23 UTC, 1Revenger1 commented on src/main/java/Core/Role/RoleUtil.java
> +package Core.Role;
Oh, maybe Core.Util? I forgot that existed.

2022-04-13 21:36 UTC, SnakeJ419 approved these changes

2022-04-13 21:36 UTC, merged